#spring.datasource.url = jdbc:mysql://localhost:3306/wzecommerce?useSSL=false
#
#spring.datasource.username =root
#
#spring.datasource.password =password
#
#spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL5Dialect
#
#spring.jpa.hibernate.ddl-auto = update

server.port: 8000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wzecommerce?useSSL=false
    username: root
    password: password
  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: update